package cc.abase.demo.component.web

import android.view.ViewGroup
import cc.ab.base.ext.*
import cc.abase.demo.R
import cc.abase.demo.component.comm.CommBindFragment
import cc.abase.demo.databinding.FragmentHtmlBinding
import cc.abase.demo.widget.HtmlWebView

/**
 * Author:Khaos116
 * Date:2022/3/15
 * Time:10:26
 */
class HtmlFragment : CommBindFragment<FragmentHtmlBinding>() {
  private val htmlCode1 =
    "<div class=\"tradingview-widget-container\">\n" +
        "  <div id=\"tradingview_ebe8e\"></div>\n" +
        "  <div class=\"tradingview-widget-copyright\"><a href=\"https://cn.tradingview.com/symbols/BETAUSDT/?exchange=BINANCE\" rel=\"noopener\" target=\"_blank\"></div>\n" +
        "  <script type=\"text/javascript\" src=\"https://s3.tradingview.com/tv.js\"></script>\n" +
        "  <script type=\"text/javascript\">\n" +
        "  new TradingView.widget(\n" +
        "  {\n" +
        "  \"autosize\": true,\n" +
        "  \"symbol\": \"BINANCE:BETAUSDT\",\n" +
        "  \"interval\": \"3\",\n" +
        "  \"timezone\": \"Etc/UTC\",\n" +
        "  \"theme\": \"light\",\n" +
        "  \"style\": \"1\",\n" +
        "  \"locale\": \"zh_CN\",\n" +
        "  \"toolbar_bg\": \"#f1f3f6\",\n" +
        "  \"enable_publishing\": false,\n" +
        "  \"hide_top_toolbar\": true,\n" +
        "  \"hide_legend\": true,\n" +
        "  \"save_image\": false,\n" +
        "  \"container_id\": \"tradingview_ebe8e\"\n" +
        "}\n" +
        "  );\n" +
        "  </script>\n" +
        "</div>"
  private var htmlCode2 = "<div class=\"article-content\">\n" +
      "<p>&nbsp;</p>\n" +
      "<div class=\"leisu-replace \" style=\"width: 720px; height: 465.12px; margin: auto; z-index: {{z_index}};\"><img src=\"https://strin.wosprdapp.net/image/news/FuyI913nX98GEK35L7sXoTmxG82F!attachment\" alt=\"1\" />\n" +
      "<div class=\"fugai dn\">&nbsp;</div>\n" +
      "</div>\n" +
      "<p>&nbsp;</p>\n" +
      "<p>北京时间2月25日，欧足联官方宣布，本赛季欧冠决赛场地将由圣彼得堡移至法国巴黎。</p>\n" +
      "<p>据悉，受乌克兰和俄罗斯局势影响，欧足联此前已经决定取消圣彼得堡的欧冠决赛举办权。</p>\n" +
      "</div>"
  private var htmlCode3 =
    "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\" align=\"center\"><em><strong><img style=\"font-family: 'microsoft yahei'; font-size: 16px; margin-left: auto; margin-right: auto; display: block !important; width: 738px; height: auto !important;\" src=\"http://www.wozuizhi.com/uploads/allimg/200429/06223S493_0.jpeg\" alt=\"中了你的毒下一句情话\" /></strong></em></p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\">&nbsp;</p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><em><strong>　　1、&ldquo;你太坏了&rdquo;&ldquo;我中了你的毒&rdquo;&ldquo;请你改邪归我&rdquo;</strong></em></p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><em><strong>　　2、&ldquo;我觉得你家里缺少一件生活必需品&rdquo;&ldquo;缺什么?&rdquo;&ldquo;缺我&rdquo;</strong></em></p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><em><strong>　　3、&ldquo;多想有一天&rdquo;&ldquo;我们不再互道晚安&rdquo;&ldquo;而是睡在彼此的身边&rdquo;</strong></em></p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><em><strong>　　4、&ldquo;你会抽烟吗?&rdquo;&ldquo;不会&rdquo;&ldquo;那你怎么美的冒烟&rdquo;</strong></em></p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><em><strong>　　5、&ldquo;你有遇到让你哭笑不得的事吗?&rdquo;&ldquo;哭也得不到你，笑也得不到你&rdquo;</strong></em></p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><em><strong>　　6、&ldquo;喜欢你是一件上瘾的事&rdquo;&ldquo;但却始终无法过瘾&rdquo;</strong></em></p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><em><strong>　　7、&ldquo;你知道你哪里好吗?&rdquo;&ldquo;哪好?&rdquo;&ldquo;做我女朋友刚刚好&rdquo;</strong></em></p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><em><strong>　　8、&ldquo;不要以为我只喜欢你&rdquo;&ldquo;我还会宠你、爱你、养你&rdquo;</strong></em></p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><em><strong>　　9、&ldquo;今天听了件很高兴的事&rdquo;&ldquo;听说。你想我了?&rdquo;</strong></em></p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><em><strong>　　10、&ldquo;我想一个人住在你心里&rdquo;&ldquo;没有邻居&rdquo;</strong></em></p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\">&nbsp;</p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\" align=\"center\"><em><strong><img style=\"font-family: 'microsoft yahei'; font-size: 16px; margin-left: auto; margin-right: auto; display: block !important; width: 738px; height: auto !important;\" src=\"http://www.wozuizhi.com/uploads/allimg/200429/0623109105_0.jpeg\" alt=\"中了你的毒的情话\" /></strong></em></p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\">&nbsp;</p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><em><strong>　　11、&ldquo;饭在锅里，人在床上&rdquo;&ldquo;先吃饭还是先吃我&rdquo;&ldquo;你随意&rdquo;</strong></em></p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><em><strong>　　12、&ldquo;你的笑&rdquo;&ldquo;温暖我的每一秒&rdquo;</strong></em></p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><em><strong>　　13、&ldquo;小哥哥网恋吧，我萝莉音&rdquo;&ldquo;小哥哥奔现吧，你已深入我心&rdquo;</strong></em></p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><em><strong>　　14、&ldquo;好想假装跑的太快&rdquo;&ldquo;然后和你撞个满怀&rdquo;</strong></em></p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><em><strong>　　15、&ldquo;我不奢望永远&rdquo;&ldquo;只希望每个明天你都在我身边&rdquo;</strong></em></p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><em><strong>　　16、&ldquo;金钱买不到快乐&rdquo;&ldquo;你买我试试，我给你乐一天&rdquo;</strong></em></p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><em><strong>　　17、&ldquo;我要是有了你&rdquo;&ldquo;我绝不碰其他女人&rdquo;</strong></em></p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><em><strong>　　18、&ldquo;如果黑夜太难熬&rdquo;&ldquo;那我陪你日夜颠倒&rdquo;</strong></em></p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><em><strong>　　19、&ldquo;别人都想要世界和平&rdquo;&ldquo;我不一样&rdquo;&ldquo;我想要世界和你&rdquo;</strong></em></p>\n" +
        "<p style=\"font-family: 'microsoft yahei'; font-size: 16px; margin: 0px; padding: 0px 0px 0.5em; list-style-type: none; clear: both; text-indent: 2em; line-height: 1.8em; color: #666666; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><em><strong>　　20、&ldquo;做我女朋友吧&rdquo;&ldquo;我手指很长&rdquo;&ldquo;而且我的舌头可以舔到鼻梁&rdquo;</strong></em></p>"

  override fun lazyInit() {
    viewBinding.flTitle.commTitleBack.pressEffectAlpha()
    viewBinding.flTitle.commTitleText.text = R.string.Html代码加载.xmlToString()
    viewBinding.flTitle.commTitleBack.click { mActivity.onBackPressed() }
    viewBinding.flWebView2.addView(HtmlWebView(mContext).also {
      it.loadHtml(
        when (System.currentTimeMillis() % 3) {
          1L -> htmlCode1
          2L -> htmlCode2
          else -> htmlCode3
        }
      )
    }, ViewGroup.LayoutParams(-1, -1))
  }
}