/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package cc.ab.base.widget.fittext.emoji.category;

import cc.ab.base.widget.fittext.emoji.GoogleEmoji;

final class ObjectsCategoryChunk0 {
  @SuppressWarnings("PMD.ExcessiveMethodLength") static GoogleEmoji[] get() {
    return new GoogleEmoji[] {
        new GoogleEmoji(0x1F453, new String[]{"eyeglasses"}, 14, 7, false),
        new GoogleEmoji(new int[] { 0x1F576, 0xFE0F }, new String[]{"dark_sunglasses"}, 29, 33, false),
        new GoogleEmoji(0x1F97D, new String[]{"goggles"}, 42, 15, false),
        new GoogleEmoji(0x1F97C, new String[]{"lab_coat"}, 42, 14, false),
        new GoogleEmoji(0x1F9BA, new String[]{"safety_vest"}, 43, 54, false),
        new GoogleEmoji(0x1F454, new String[]{"necktie"}, 14, 8, false),
        new GoogleEmoji(0x1F455, new String[]{"shirt", "tshirt"}, 14, 9, false),
        new GoogleEmoji(0x1F456, new String[]{"jeans"}, 14, 10, false),
        new GoogleEmoji(0x1F9E3, new String[]{"scarf"}, 51, 22, false),
        new GoogleEmoji(0x1F9E4, new String[]{"gloves"}, 51, 23, false),
        new GoogleEmoji(0x1F9E5, new String[]{"coat"}, 51, 24, false),
        new GoogleEmoji(0x1F9E6, new String[]{"socks"}, 51, 25, false),
        new GoogleEmoji(0x1F457, new String[]{"dress"}, 14, 11, false),
        new GoogleEmoji(0x1F458, new String[]{"kimono"}, 14, 12, false),
        new GoogleEmoji(0x1F97B, new String[]{"sari"}, 42, 13, false),
        new GoogleEmoji(0x1FA71, new String[]{"one-piece_swimsuit"}, 51, 52, false),
        new GoogleEmoji(0x1FA72, new String[]{"briefs"}, 51, 53, false),
        new GoogleEmoji(0x1FA73, new String[]{"shorts"}, 51, 54, false),
        new GoogleEmoji(0x1F459, new String[]{"bikini"}, 14, 13, false),
        new GoogleEmoji(0x1F45A, new String[]{"womans_clothes"}, 14, 14, false),
        new GoogleEmoji(0x1F45B, new String[]{"purse"}, 14, 15, false),
        new GoogleEmoji(0x1F45C, new String[]{"handbag"}, 14, 16, false),
        new GoogleEmoji(0x1F45D, new String[]{"pouch"}, 14, 17, false),
        new GoogleEmoji(new int[] { 0x1F6CD, 0xFE0F }, new String[]{"shopping_bags"}, 36, 35, false),
        new GoogleEmoji(0x1F392, new String[]{"school_satchel"}, 7, 54, false),
        new GoogleEmoji(0x1F45E, new String[]{"mans_shoe", "shoe"}, 14, 18, false),
        new GoogleEmoji(0x1F45F, new String[]{"athletic_shoe"}, 14, 19, false),
        new GoogleEmoji(0x1F97E, new String[]{"hiking_boot"}, 42, 16, false),
        new GoogleEmoji(0x1F97F, new String[]{"womans_flat_shoe"}, 42, 17, false),
        new GoogleEmoji(0x1F460, new String[]{"high_heel"}, 14, 20, false),
        new GoogleEmoji(0x1F461, new String[]{"sandal"}, 14, 21, false),
        new GoogleEmoji(0x1FA70, new String[]{"ballet_shoes"}, 51, 51, false),
        new GoogleEmoji(0x1F462, new String[]{"boot"}, 14, 22, false),
        new GoogleEmoji(0x1F451, new String[]{"crown"}, 14, 5, false),
        new GoogleEmoji(0x1F452, new String[]{"womans_hat"}, 14, 6, false),
        new GoogleEmoji(0x1F3A9, new String[]{"tophat"}, 8, 15, false),
        new GoogleEmoji(0x1F393, new String[]{"mortar_board"}, 7, 55, false),
        new GoogleEmoji(0x1F9E2, new String[]{"billed_cap"}, 51, 21, false),
        new GoogleEmoji(new int[] { 0x26D1, 0xFE0F }, new String[]{"helmet_with_white_cross"}, 54, 6, false),
        new GoogleEmoji(0x1F4FF, new String[]{"prayer_beads"}, 27, 27, false),
        new GoogleEmoji(0x1F484, new String[]{"lipstick"}, 24, 32, false),
        new GoogleEmoji(0x1F48D, new String[]{"ring"}, 25, 23, false),
        new GoogleEmoji(0x1F48E, new String[]{"gem"}, 25, 24, false),
        new GoogleEmoji(0x1F507, new String[]{"mute"}, 27, 35, false),
        new GoogleEmoji(0x1F508, new String[]{"speaker"}, 27, 36, false),
        new GoogleEmoji(0x1F509, new String[]{"sound"}, 27, 37, false),
        new GoogleEmoji(0x1F50A, new String[]{"loud_sound"}, 27, 38, false),
        new GoogleEmoji(0x1F4E2, new String[]{"loudspeaker"}, 26, 56, false),
        new GoogleEmoji(0x1F4E3, new String[]{"mega"}, 27, 0, false),
        new GoogleEmoji(0x1F4EF, new String[]{"postal_horn"}, 27, 12, false),
        new GoogleEmoji(0x1F514, new String[]{"bell"}, 27, 48, false),
        new GoogleEmoji(0x1F515, new String[]{"no_bell"}, 27, 49, false),
        new GoogleEmoji(0x1F3BC, new String[]{"musical_score"}, 8, 34, false),
        new GoogleEmoji(0x1F3B5, new String[]{"musical_note"}, 8, 27, false),
        new GoogleEmoji(0x1F3B6, new String[]{"notes"}, 8, 28, false),
        new GoogleEmoji(new int[] { 0x1F399, 0xFE0F }, new String[]{"studio_microphone"}, 8, 1, false),
        new GoogleEmoji(new int[] { 0x1F39A, 0xFE0F }, new String[]{"level_slider"}, 8, 2, false),
        new GoogleEmoji(new int[] { 0x1F39B, 0xFE0F }, new String[]{"control_knobs"}, 8, 3, false),
        new GoogleEmoji(0x1F3A4, new String[]{"microphone"}, 8, 10, false),
        new GoogleEmoji(0x1F3A7, new String[]{"headphones"}, 8, 13, false),
        new GoogleEmoji(0x1F4FB, new String[]{"radio"}, 27, 24, false),
        new GoogleEmoji(0x1F3B7, new String[]{"saxophone"}, 8, 29, false),
        new GoogleEmoji(0x1F3B8, new String[]{"guitar"}, 8, 30, false),
        new GoogleEmoji(0x1F3B9, new String[]{"musical_keyboard"}, 8, 31, false),
        new GoogleEmoji(0x1F3BA, new String[]{"trumpet"}, 8, 32, false),
        new GoogleEmoji(0x1F3BB, new String[]{"violin"}, 8, 33, false),
        new GoogleEmoji(0x1FA95, new String[]{"banjo"}, 52, 9, false),
        new GoogleEmoji(0x1F941, new String[]{"drum_with_drumsticks"}, 41, 17, false),
        new GoogleEmoji(0x1F4F1, new String[]{"iphone"}, 27, 14, false),
        new GoogleEmoji(0x1F4F2, new String[]{"calling"}, 27, 15, false),
        new GoogleEmoji(new int[] { 0x260E, 0xFE0F }, new String[]{"phone", "telephone"}, 52, 54, false),
        new GoogleEmoji(0x1F4DE, new String[]{"telephone_receiver"}, 26, 52, false),
        new GoogleEmoji(0x1F4DF, new String[]{"pager"}, 26, 53, false),
        new GoogleEmoji(0x1F4E0, new String[]{"fax"}, 26, 54, false),
        new GoogleEmoji(0x1F50B, new String[]{"battery"}, 27, 39, false),
        new GoogleEmoji(0x1F50C, new String[]{"electric_plug"}, 27, 40, false),
        new GoogleEmoji(0x1F4BB, new String[]{"computer"}, 26, 17, false),
        new GoogleEmoji(new int[] { 0x1F5A5, 0xFE0F }, new String[]{"desktop_computer"}, 30, 10, false),
        new GoogleEmoji(new int[] { 0x1F5A8, 0xFE0F }, new String[]{"printer"}, 30, 11, false),
        new GoogleEmoji(new int[] { 0x2328, 0xFE0F }, new String[]{"keyboard"}, 52, 24, false),
        new GoogleEmoji(new int[] { 0x1F5B1, 0xFE0F }, new String[]{"three_button_mouse"}, 30, 12, false),
        new GoogleEmoji(new int[] { 0x1F5B2, 0xFE0F }, new String[]{"trackball"}, 30, 13, false),
        new GoogleEmoji(0x1F4BD, new String[]{"minidisc"}, 26, 19, false),
        new GoogleEmoji(0x1F4BE, new String[]{"floppy_disk"}, 26, 20, false),
        new GoogleEmoji(0x1F4BF, new String[]{"cd"}, 26, 21, false),
        new GoogleEmoji(0x1F4C0, new String[]{"dvd"}, 26, 22, false),
        new GoogleEmoji(0x1F9EE, new String[]{"abacus"}, 51, 33, false),
        new GoogleEmoji(0x1F3A5, new String[]{"movie_camera"}, 8, 11, false),
        new GoogleEmoji(new int[] { 0x1F39E, 0xFE0F }, new String[]{"film_frames"}, 8, 4, false),
        new GoogleEmoji(new int[] { 0x1F4FD, 0xFE0F }, new String[]{"film_projector"}, 27, 26, false),
        new GoogleEmoji(0x1F3AC, new String[]{"clapper"}, 8, 18, false),
        new GoogleEmoji(0x1F4FA, new String[]{"tv"}, 27, 23, false),
        new GoogleEmoji(0x1F4F7, new String[]{"camera"}, 27, 20, false),
        new GoogleEmoji(0x1F4F8, new String[]{"camera_with_flash"}, 27, 21, false),
        new GoogleEmoji(0x1F4F9, new String[]{"video_camera"}, 27, 22, false),
        new GoogleEmoji(0x1F4FC, new String[]{"vhs"}, 27, 25, false),
        new GoogleEmoji(0x1F50D, new String[]{"mag"}, 27, 41, false),
        new GoogleEmoji(0x1F50E, new String[]{"mag_right"}, 27, 42, false),
        new GoogleEmoji(new int[] { 0x1F56F, 0xFE0F }, new String[]{"candle"}, 29, 6, false),
        new GoogleEmoji(0x1F4A1, new String[]{"bulb"}, 25, 43, false),
        new GoogleEmoji(0x1F526, new String[]{"flashlight"}, 28, 9, false),
        new GoogleEmoji(0x1F3EE, new String[]{"izakaya_lantern", "lantern"}, 11, 8, false),
        new GoogleEmoji(0x1FA94, new String[]{"diya_lamp"}, 52, 8, false),
        new GoogleEmoji(0x1F4D4, new String[]{"notebook_with_decorative_cover"}, 26, 42, false),
        new GoogleEmoji(0x1F4D5, new String[]{"closed_book"}, 26, 43, false),
        new GoogleEmoji(0x1F4D6, new String[]{"book", "open_book"}, 26, 44, false),
        new GoogleEmoji(0x1F4D7, new String[]{"green_book"}, 26, 45, false),
        new GoogleEmoji(0x1F4D8, new String[]{"blue_book"}, 26, 46, false),
        new GoogleEmoji(0x1F4D9, new String[]{"orange_book"}, 26, 47, false),
        new GoogleEmoji(0x1F4DA, new String[]{"books"}, 26, 48, false),
        new GoogleEmoji(0x1F4D3, new String[]{"notebook"}, 26, 41, false),
        new GoogleEmoji(0x1F4D2, new String[]{"ledger"}, 26, 40, false),
        new GoogleEmoji(0x1F4C3, new String[]{"page_with_curl"}, 26, 25, false),
        new GoogleEmoji(0x1F4DC, new String[]{"scroll"}, 26, 50, false),
        new GoogleEmoji(0x1F4C4, new String[]{"page_facing_up"}, 26, 26, false),
        new GoogleEmoji(0x1F4F0, new String[]{"newspaper"}, 27, 13, false),
        new GoogleEmoji(new int[] { 0x1F5DE, 0xFE0F }, new String[]{"rolled_up_newspaper"}, 30, 23, false),
        new GoogleEmoji(0x1F4D1, new String[]{"bookmark_tabs"}, 26, 39, false),
        new GoogleEmoji(0x1F516, new String[]{"bookmark"}, 27, 50, false),
        new GoogleEmoji(new int[] { 0x1F3F7, 0xFE0F }, new String[]{"label"}, 11, 19, false),
        new GoogleEmoji(0x1F4B0, new String[]{"moneybag"}, 26, 6, false),
        new GoogleEmoji(0x1F4B4, new String[]{"yen"}, 26, 10, false),
        new GoogleEmoji(0x1F4B5, new String[]{"dollar"}, 26, 11, false),
        new GoogleEmoji(0x1F4B6, new String[]{"euro"}, 26, 12, false),
        new GoogleEmoji(0x1F4B7, new String[]{"pound"}, 26, 13, false),
        new GoogleEmoji(0x1F4B8, new String[]{"money_with_wings"}, 26, 14, false),
        new GoogleEmoji(0x1F4B3, new String[]{"credit_card"}, 26, 9, false),
        new GoogleEmoji(0x1F9FE, new String[]{"receipt"}, 51, 49, false),
        new GoogleEmoji(0x1F4B9, new String[]{"chart"}, 26, 15, false),
        new GoogleEmoji(0x1F4B1, new String[]{"currency_exchange"}, 26, 7, false),
        new GoogleEmoji(0x1F4B2, new String[]{"heavy_dollar_sign"}, 26, 8, false),
        new GoogleEmoji(new int[] { 0x2709, 0xFE0F }, new String[]{"email", "envelope"}, 54, 42, false),
        new GoogleEmoji(0x1F4E7, new String[]{"e-mail"}, 27, 4, false),
        new GoogleEmoji(0x1F4E8, new String[]{"incoming_envelope"}, 27, 5, false),
        new GoogleEmoji(0x1F4E9, new String[]{"envelope_with_arrow"}, 27, 6, false),
        new GoogleEmoji(0x1F4E4, new String[]{"outbox_tray"}, 27, 1, false),
        new GoogleEmoji(0x1F4E5, new String[]{"inbox_tray"}, 27, 2, false),
        new GoogleEmoji(0x1F4E6, new String[]{"package"}, 27, 3, false),
        new GoogleEmoji(0x1F4EB, new String[]{"mailbox"}, 27, 8, false),
        new GoogleEmoji(0x1F4EA, new String[]{"mailbox_closed"}, 27, 7, false),
        new GoogleEmoji(0x1F4EC, new String[]{"mailbox_with_mail"}, 27, 9, false),
        new GoogleEmoji(0x1F4ED, new String[]{"mailbox_with_no_mail"}, 27, 10, false),
        new GoogleEmoji(0x1F4EE, new String[]{"postbox"}, 27, 11, false),
        new GoogleEmoji(new int[] { 0x1F5F3, 0xFE0F }, new String[]{"ballot_box_with_ballot"}, 30, 28, false),
        new GoogleEmoji(new int[] { 0x270F, 0xFE0F }, new String[]{"pencil2"}, 55, 10, false),
        new GoogleEmoji(new int[] { 0x2712, 0xFE0F }, new String[]{"black_nib"}, 55, 11, false),
        new GoogleEmoji(new int[] { 0x1F58B, 0xFE0F }, new String[]{"lower_left_fountain_pen"}, 29, 45, false),
        new GoogleEmoji(new int[] { 0x1F58A, 0xFE0F }, new String[]{"lower_left_ballpoint_pen"}, 29, 44, false),
        new GoogleEmoji(new int[] { 0x1F58C, 0xFE0F }, new String[]{"lower_left_paintbrush"}, 29, 46, false),
        new GoogleEmoji(new int[] { 0x1F58D, 0xFE0F }, new String[]{"lower_left_crayon"}, 29, 47, false),
        new GoogleEmoji(0x1F4DD, new String[]{"memo", "pencil"}, 26, 51, false),
        new GoogleEmoji(0x1F4BC, new String[]{"briefcase"}, 26, 18, false),
        new GoogleEmoji(0x1F4C1, new String[]{"file_folder"}, 26, 23, false),
        new GoogleEmoji(0x1F4C2, new String[]{"open_file_folder"}, 26, 24, false),
        new GoogleEmoji(new int[] { 0x1F5C2, 0xFE0F }, new String[]{"card_index_dividers"}, 30, 15, false),
        new GoogleEmoji(0x1F4C5, new String[]{"date"}, 26, 27, false),
        new GoogleEmoji(0x1F4C6, new String[]{"calendar"}, 26, 28, false),
        new GoogleEmoji(new int[] { 0x1F5D2, 0xFE0F }, new String[]{"spiral_note_pad"}, 30, 19, false),
        new GoogleEmoji(new int[] { 0x1F5D3, 0xFE0F }, new String[]{"spiral_calendar_pad"}, 30, 20, false),
        new GoogleEmoji(0x1F4C7, new String[]{"card_index"}, 26, 29, false),
        new GoogleEmoji(0x1F4C8, new String[]{"chart_with_upwards_trend"}, 26, 30, false),
        new GoogleEmoji(0x1F4C9, new String[]{"chart_with_downwards_trend"}, 26, 31, false),
        new GoogleEmoji(0x1F4CA, new String[]{"bar_chart"}, 26, 32, false),
        new GoogleEmoji(0x1F4CB, new String[]{"clipboard"}, 26, 33, false),
        new GoogleEmoji(0x1F4CC, new String[]{"pushpin"}, 26, 34, false),
        new GoogleEmoji(0x1F4CD, new String[]{"round_pushpin"}, 26, 35, false),
        new GoogleEmoji(0x1F4CE, new String[]{"paperclip"}, 26, 36, false),
        new GoogleEmoji(new int[] { 0x1F587, 0xFE0F }, new String[]{"linked_paperclips"}, 29, 43, false),
        new GoogleEmoji(0x1F4CF, new String[]{"straight_ruler"}, 26, 37, false),
        new GoogleEmoji(0x1F4D0, new String[]{"triangular_ruler"}, 26, 38, false),
        new GoogleEmoji(new int[] { 0x2702, 0xFE0F }, new String[]{"scissors"}, 54, 39, false),
        new GoogleEmoji(new int[] { 0x1F5C3, 0xFE0F }, new String[]{"card_file_box"}, 30, 16, false),
        new GoogleEmoji(new int[] { 0x1F5C4, 0xFE0F }, new String[]{"file_cabinet"}, 30, 17, false),
        new GoogleEmoji(new int[] { 0x1F5D1, 0xFE0F }, new String[]{"wastebasket"}, 30, 18, false),
        new GoogleEmoji(0x1F512, new String[]{"lock"}, 27, 46, false),
        new GoogleEmoji(0x1F513, new String[]{"unlock"}, 27, 47, false),
        new GoogleEmoji(0x1F50F, new String[]{"lock_with_ink_pen"}, 27, 43, false),
        new GoogleEmoji(0x1F510, new String[]{"closed_lock_with_key"}, 27, 44, false),
        new GoogleEmoji(0x1F511, new String[]{"key"}, 27, 45, false),
        new GoogleEmoji(new int[] { 0x1F5DD, 0xFE0F }, new String[]{"old_key"}, 30, 22, false),
        new GoogleEmoji(0x1F528, new String[]{"hammer"}, 28, 11, false),
        new GoogleEmoji(0x1FA93, new String[]{"axe"}, 52, 7, false),
        new GoogleEmoji(new int[] { 0x26CF, 0xFE0F }, new String[]{"pick"}, 54, 5, false),
        new GoogleEmoji(new int[] { 0x2692, 0xFE0F }, new String[]{"hammer_and_pick"}, 53, 41, false),
        new GoogleEmoji(new int[] { 0x1F6E0, 0xFE0F }, new String[]{"hammer_and_wrench"}, 36, 42, false),
        new GoogleEmoji(new int[] { 0x1F5E1, 0xFE0F }, new String[]{"dagger_knife"}, 30, 24, false),
        new GoogleEmoji(new int[] { 0x2694, 0xFE0F }, new String[]{"crossed_swords"}, 53, 43, false),
        new GoogleEmoji(0x1F52B, new String[]{"gun"}, 28, 14, false),
        new GoogleEmoji(0x1F3F9, new String[]{"bow_and_arrow"}, 11, 21, false),
        new GoogleEmoji(new int[] { 0x1F6E1, 0xFE0F }, new String[]{"shield"}, 36, 43, false),
        new GoogleEmoji(0x1F527, new String[]{"wrench"}, 28, 10, false),
        new GoogleEmoji(0x1F529, new String[]{"nut_and_bolt"}, 28, 12, false),
        new GoogleEmoji(new int[] { 0x2699, 0xFE0F }, new String[]{"gear"}, 53, 47, false),
        new GoogleEmoji(new int[] { 0x1F5DC, 0xFE0F }, new String[]{"compression"}, 30, 21, false),
        new GoogleEmoji(new int[] { 0x2696, 0xFE0F }, new String[]{"scales"}, 53, 45, false),
        new GoogleEmoji(0x1F9AF, new String[]{"probing_cane"}, 43, 3, false),
        new GoogleEmoji(0x1F517, new String[]{"link"}, 27, 51, false),
        new GoogleEmoji(new int[] { 0x26D3, 0xFE0F }, new String[]{"chains"}, 54, 7, false),
        new GoogleEmoji(0x1F9F0, new String[]{"toolbox"}, 51, 35, false),
        new GoogleEmoji(0x1F9F2, new String[]{"magnet"}, 51, 37, false),
        new GoogleEmoji(new int[] { 0x2697, 0xFE0F }, new String[]{"alembic"}, 53, 46, false),
        new GoogleEmoji(0x1F9EA, new String[]{"test_tube"}, 51, 29, false),
        new GoogleEmoji(0x1F9EB, new String[]{"petri_dish"}, 51, 30, false),
        new GoogleEmoji(0x1F9EC, new String[]{"dna"}, 51, 31, false),
        new GoogleEmoji(0x1F52C, new String[]{"microscope"}, 28, 15, false),
        new GoogleEmoji(0x1F52D, new String[]{"telescope"}, 28, 16, false),
        new GoogleEmoji(0x1F4E1, new String[]{"satellite_antenna"}, 26, 55, false),
        new GoogleEmoji(0x1F489, new String[]{"syringe"}, 25, 19, false),
        new GoogleEmoji(0x1FA78, new String[]{"drop_of_blood"}, 51, 55, false),
        new GoogleEmoji(0x1F48A, new String[]{"pill"}, 25, 20, false),
        new GoogleEmoji(0x1FA79, new String[]{"adhesive_bandage"}, 51, 56, false),
        new GoogleEmoji(0x1FA7A, new String[]{"stethoscope"}, 52, 0, false),
        new GoogleEmoji(0x1F6AA, new String[]{"door"}, 35, 1, false),
        new GoogleEmoji(new int[] { 0x1F6CF, 0xFE0F }, new String[]{"bed"}, 36, 37, false),
        new GoogleEmoji(new int[] { 0x1F6CB, 0xFE0F }, new String[]{"couch_and_lamp"}, 36, 28, false),
        new GoogleEmoji(0x1FA91, new String[]{"chair"}, 52, 5, false),
        new GoogleEmoji(0x1F6BD, new String[]{"toilet"}, 36, 14, false),
        new GoogleEmoji(0x1F6BF, new String[]{"shower"}, 36, 16, false),
        new GoogleEmoji(0x1F6C1, new String[]{"bathtub"}, 36, 23, false),
        new GoogleEmoji(0x1FA92, new String[]{"razor"}, 52, 6, false),
        new GoogleEmoji(0x1F9F4, new String[]{"lotion_bottle"}, 51, 39, false),
        new GoogleEmoji(0x1F9F7, new String[]{"safety_pin"}, 51, 42, false),
        new GoogleEmoji(0x1F9F9, new String[]{"broom"}, 51, 44, false),
        new GoogleEmoji(0x1F9FA, new String[]{"basket"}, 51, 45, false),
        new GoogleEmoji(0x1F9FB, new String[]{"roll_of_paper"}, 51, 46, false),
        new GoogleEmoji(0x1F9FC, new String[]{"soap"}, 51, 47, false),
        new GoogleEmoji(0x1F9FD, new String[]{"sponge"}, 51, 48, false),
        new GoogleEmoji(0x1F9EF, new String[]{"fire_extinguisher"}, 51, 34, false),
        new GoogleEmoji(0x1F6D2, new String[]{"shopping_trolley"}, 36, 40, false),
        new GoogleEmoji(0x1F6AC, new String[]{"smoking"}, 35, 3, false),
        new GoogleEmoji(new int[] { 0x26B0, 0xFE0F }, new String[]{"coffin"}, 53, 54, false),
        new GoogleEmoji(new int[] { 0x26B1, 0xFE0F }, new String[]{"funeral_urn"}, 53, 55, false),
        new GoogleEmoji(0x1F5FF, new String[]{"moyai"}, 30, 34, false)
    };
  }

  private ObjectsCategoryChunk0() {
    // No instances.
  }
}